import '.././styles/globals.css'
import Header from './HomeComponents/header'
import Footer from './HomeComponents/footer';
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { headers } from 'next/headers'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}